### PR TITLE
Allow custom error in @:restrict

### PR DESCRIPTION
**Pull request by kevinresol**

### CODE REVIEW

**Comment by back2dos** [comment]
This strikes me as somewhat redundant, since the expression in `@:restrict` can already return an error. If you really need it, feel free to merge. I'd still like to understand the use case here though, for that fine day in the hopefully not too distant future when we're going to document when this feature should be used.

**Comment by kevinresol** [comment]
I am trying to build microservice system. A few servers of different functions are running in parallel and they will call each others' API. Since the errors are propagated automatically by Promise, I get no idea where the error originates from, because it is always the same message "forbidden" being thrown at my face. So basically I would like to make the error somewhat more meaningful, and that's why I need a way to customize it.

**Comment by kevinresol** [comment]
It is also easier to debug when one have multiple `@:restrict` on the same route.
Because you can produce a different error for each of them, so that you know which one is actually failing.

**Comment by back2dos** [comment]
I see I was unclear. I absolutely understand the need to produce custom errors from restrict clauses, but that's already possible, hence my my question. Let me boil down my question to this: What's the advantage of the second of these two versions?

```haxe
@:restrict(new tink.core.Error(Conflict, 'custom message')) 
@:get public function customForbid() return 'nope';

@:restrict(false, new tink.core.Error(Conflict, 'custom message')) 
@:get public function customForbid() return 'nope';
```

**Comment by kevinresol** [comment]
That's simply because my brain fails to realize `Error` is `Promise`.  I better go get some good sleep. 😂

**Pull request closed without merging**
