### PR TITLE
`user` special argument and `proxy.Remote`

### PR DESCRIPTION
**Pull request by emugel**

### CODE REVIEW

**Comment by kevinresol** [comment]
I am not very sure what is the key message to be delivered here. Because "implementation of an interface must has the exact signature" is Haxe feature. Not a tink_web one.

**Comment by emugel** [comment]
This is related to the question I asked you on gitter. The removal of `user` is produced by a macro, therefore I think it has to be documented somewhere.

**Comment by kevinresol** [comment]
Personally I found it confusing (perhaps it is a matter of the wording). Because it says Remote needs to implement user but then it says on client side it would be removed

**Comment by emugel** [comment]
Maybe the phrasing is not clear 

But it doesn’t  use the word `implement`:

If you use this approach and have a interface defined for your API with `tink.web.proxy.Remote`, the interface methods must also have the `user` argument; on the client-side the `user` parameter is removed on the Remote.

**Comment by emugel** [comment]
Maybe it’s because I used the word method instead of function you had this impression

**Comment by kevinresol** [comment]
I think the key problem is this sentence, which is ambiguous and I don't really get what it means:

> have a interface defined for your API with tink.web.proxy.Remote

I prefer a simple sentence about remote:

```
When wrapped by a `Remote` (link to remoting page), the `user` argument is removed.
```

What do you think?

**Comment by emugel** [comment]
Yes, think it works!

**Comment by kevinresol** [comment]
Thanks 🙏

**Pull request merged**
