### PR TITLE
In TestProxy could we use new RemoteEndpoint(null) for LocalContainer?

### PR DESCRIPTION
**Pull request by emugel**
Right now we have `proxy = new Remote<Fake>(client, new RemoteEndpoint(new Host('localhost', 80)));`. Can we use the convention `proxy = new Remote<Fake>(client, new RemoteEndpoint(null));` here? 

I can see how it could be controversial (usually I would say `null` is not the tink way) but 

1. `new Host('localhost', 80)` is misleading since there is no listening socket in this case, and 
2. creating another type of `Remote` just for LocalContainer would be overkill. 

So which is better in your opinion, some fake `Host` or `null`?

### CODE REVIEW

**Comment by emugel** [comment]
If using a host we may want 255.255.255.255 which is completely unroutable by definition, and thus more semantically correct.

But it will not be necessary more clear than 127.0.0.1:80 to the occasional code reviewer.
So, as a third proposal, we could have a `Host.none()` which would return e.g. `new Host("255.255.255.255", 0xFFFF)`  and then `proxy = new Remote<Fake>(client, new RemoteEndpoint(Host.none()));`

**Comment by kevinresol** [comment]
> 1. is misleading

Yes it is technically "wrong" to provide a Host. But I don't see what harm it brings. But since anything is fine here, I am fine with anything.

**Comment by back2dos** [comment]
The handler in `LocalContainer` could in theory respond depending on the host header. Not the case for the tests though. I wonder if `new Host("ignored")` isn't just as explicit, while not passing around null - which will become an annoyance if we ever try to use null safety.

**Comment by emugel** [comment]
Yes that's what I fear with null. That it introduces uncertainties and worst that one day it could induce bugs in a system.

I think `Host.none()` (`= new Host("")`)  has an advantage over `new Host("ignored")`. 
Because technically any word may be defined as a single word domain name (e.g. a line containing "ignored" in `/etc/hosts`). OTOH "" is always guaranteed to be non-routable. It is of course cosmetic, like kevin said we just can put whatever, but if we give a definition "" seems better because of that.

Also a static function `Host.none()` has another advantage, that when we choose to document `LocalContainer` the programmer don't have to introduce creative variations around `proxy = new Remote<Fake>(client, new RemoteEndpoint(new Host("ignored"))`. 

With `proxy = new Remote<Fake>(client, new RemoteEndpoint(Host.none())` in the doc or in this TestProxy file, for the programmer there's just less room for creativity around researching if he wants to changed "ignored" to something else. Mind is clear from doubt.

**Comment by emugel** [comment]
Ok closing this, as juraj said for now `Host("ignored")` can be used

**Pull request closed without merging**
