### PR TITLE
Add tink_xml support.

### PR DESCRIPTION
**Pull request by piboistudios**
Tried to keep it from obliterating the git blame via whitespace as best I could.

### CODE REVIEW

**Comment by kevinresol** [comment]
Can you also add a test?

**Comment by kevinresol** [comment]
what are those binary files?

**Comment by back2dos** [comment]
Indeed: what are those binary files? ^^

**Comment by emugel** [comment]
+1 for the test, and maybe a documentation update if accepted, 
I'm quite interested by this xml feature but without the test I won't figure it out :)

**Comment by piboistudios** [comment]
@kevinresol @back2dos no idea. Probably some workspace/debugging stuff I forgot to gitignore.

I will close this for now for reasons along the lines of what @emugel stated.

Tests can be written, surely, but I would like the tests to be almost identical if not the same as JSON tests, and that's not currently possible without a tink_xml writer.

**Pull request closed without merging**
