### PR TITLE
Add remote proxying. Fix incorrect type in macro

### PR DESCRIPTION
**Pull request by piboistudios**
This will allow you to return `tink.web.proxy.Remote` instances from routes like so:
```haxe
	@:sub("/@me")
	@:async public function me(user:Session.User):tink.web.proxy.Remote<UserProxy> {
		return duckProxy.users(AppSettings.config.wildDuck.apiKey).get(user.duck.id);
	}
```
Then, using [this](https://github.com/Brave-Pi/bp_duck/blob/master/src/bp/duck/proxy/WildDuckProxy.hx#L150) remote interface as an example:
```http
GET /api/@me/mailboxes/61cbf39ac3b56500072d77d8/messages/18 HTTP/1.1
Host: localhost:3000
Content-Type: application/json
x-access-token: <access-token>
{
	"username": "<username>",
	"password": "<password>"
}------WebKitFormBoundary7MA4YWxkTrZu0gW--
```

Response:
```haxe
{
    "answered": false,
    "attachments": [],
    "contentType": {
        "params": {
            "boundary": "000000000000df2f8705d53e1902"
        },
        "value": "multipart/alternative"
    },
    "date": "2022-01-10T17:59:31.000Z",
    "deleted": false,
    "draft": false,
    "envelope": {
        "from": "gabriel.speed.bullock@gmail.com",
        "rcpt": [
            {
                "formatted": "webmaster@gabedev.tech",
                "value": "webmaster@gabedev.tech"
            }
        ]
    },
    "flagged": false,
    "forwarded": false,
    "from": {
        "address": "gabriel.speed.bullock@gmail.com",
        "name": "Gabriel Speed"
    },
    "html": [
        "<div dir=\"auto\">You made the Protoverse, Usernet, GunChain and Boisly</div>"
    ],
    "id": 18,
    "mailbox": "61cbf39ac3b56500072d77d8",
    "messageId": "<CAFoxTFqQo5XsNbX-6QA+X+60TWY0CY7f5p4+ZUYtcHbuz3+R4Q@mail.gmail.com>",
    "metaData": {},
    "seen": false,
    "size": 3565,
    "subject": "Protoverse",
    "success": true,
    "text": "You made the Protoverse, Usernet, GunChain and Boisly",
    "thread": "61dc740fe9e4e70012b37833",
    "to": [
        {
            "address": "gabe4haxelang@gmail.com",
            "name": ""
        },
        {
            "address": "webmaster@gabedev.tech",
            "name": ""
        }
    ],
    "user": "61cbf39ac3b56500072d77d7",
    "verificationResults": {
        "dkim": "gmail.com",
        "spf": "gmail.com",
        "tls": {
            "name": "TLS_AES_256_GCM_SHA384",
            "version": "TLSv1.3"
        }
    }
}
```

### CODE REVIEW

**Comment by back2dos** [comment]
Any idea what's going on with the disabled test? Otherwise, I'll try to check it this weekend ;)

**Comment by piboistudios** [comment]
> Any idea what's going on with the disabled test? Otherwise, I'll try to check it this weekend ;)

Not really. I had to make it dynamic, and also `scheme` is actually `undefined` (or `null` in Haxe) and not `''` as the test case was expecting..

**Comment by emugel** [comment]
kind of like a symlink for APIs?
I really like it

**Review by kevinresol — APPROVED** [review]

**Comment by kevinresol** [comment]
or can you just leave the issue123 test unchanged? we can deal with it in another issue if it is still a problem

**Comment by kevinresol** [comment]
> or can you just leave the issue123 test unchanged? we can deal with it in another issue if it is still a problem

Can you do it in a way such that it shows no changes in this PR?

**Comment by piboistudios** [comment]
> > or can you just leave the issue123 test unchanged? we can deal with it in another issue if it is still a problem
> 
> Can you do it in a way such that it shows no changes in this PR?

Yeah, I am not really sure how to do that without opening another PR

**Comment by kevinresol** [comment]
Keep committing until the changes disappear in the "Changes" tab in this PR

**Comment by piboistudios** [comment]
Yeah, probably instead I just won't make anymore pull requests :). Make it yourself.

**Pull request closed without merging**
